@extends('layouts.app')

@section('title', 'Generate Vouchers')

@section('content')
<div class="min-h-screen bg-gray-100" x-data="{ sidebarOpen: false }">
    @include('admin.partials.sidebar')
    <div class="lg:pl-64">
        @include('admin.partials.topbar')
        <div class="p-6">
            <div class="mb-6">
                <h1 class="text-3xl font-bold text-gray-900">Generate Hotspot Vouchers</h1>
            </div>
            <div class="max-w-2xl">
                <div class="bg-white rounded-xl shadow-sm p-6">
                    <form action="{{ route('admin.hotspot.vouchers.store') }}" method="POST">
                        @csrf
                        <div class="space-y-4">
                            <div class="grid grid-cols-2 gap-4">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-1">Quantity *</label>
                                    <input type="number" name="quantity" value="{{ old('quantity', 10) }}" required min="1" max="1000" class="w-full px-4 py-2 border rounded-lg">
                                </div>
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-1">Profile *</label>
                                    <select name="profile_id" required class="w-full px-4 py-2 border rounded-lg">
                                        <option value="">Select Profile</option>
                                        @foreach($profiles as $profile)
                                            <option value="{{ $profile->id }}">{{ $profile->name }} - {{ $profile->formatted_price }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="grid grid-cols-2 gap-4">
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-1">Username Prefix</label>
                                    <input type="text" name="prefix" value="{{ old('prefix', 'VC') }}" maxlength="10" class="w-full px-4 py-2 border rounded-lg">
                                </div>
                                <div>
                                    <label class="block text-sm font-medium text-gray-700 mb-1">Random Length</label>
                                    <input type="number" name="length" value="{{ old('length', 6) }}" min="4" max="12" class="w-full px-4 py-2 border rounded-lg">
                                </div>
                            </div>
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-1">Time Limit</label>
                                <input type="text" name="limit_uptime" value="{{ old('limit_uptime') }}" class="w-full px-4 py-2 border rounded-lg" placeholder="e.g., 1h, 1d, 7d">
                            </div>
                            <div>
                                <label class="block text-sm font-medium text-gray-700 mb-1">Comment</label>
                                <input type="text" name="comment" value="{{ old('comment', 'Generated by Gembok') }}" class="w-full px-4 py-2 border rounded-lg">
                            </div>
                            <div class="flex items-center space-x-4">
                                <label class="flex items-center"><input type="checkbox" name="sync_to_mikrotik" value="1" checked class="mr-2"> Sync to Mikrotik</label>
                                <label class="flex items-center"><input type="checkbox" name="print_vouchers" value="1" class="mr-2"> Print after generate</label>
                            </div>
                        </div>
                        <div class="mt-6 flex justify-end space-x-3">
                            <a href="{{ route('admin.hotspot.vouchers') }}" class="px-4 py-2 text-gray-700">Cancel</a>
                            <button type="submit" class="px-6 py-2 bg-cyan-600 text-white rounded-lg hover:bg-cyan-700"><i class="fas fa-magic mr-2"></i> Generate</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
